"""
Django settings for MirrorMind project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── GENAI API Keys from .env ──
GENAI_API_KEYS = [
    key
    for key in [
        os.getenv("GENAI_API_KEY_1"),
        os.getenv("GENAI_API_KEY_2"),
        os.getenv("GENAI_API_KEY_3"),
    ]
    if key
]

# ── Secret Key from .env ──
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-key-only-for-dev")

# ── Debug: Local = True, Production = False ──
DEBUG = False

# ── Allowed Hosts ──
ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    # ── Deploy keltyanar tumcha domain ithe add kara ──
    # "https://tumcha-domain.com",
    # "https://www.tumcha-domain.com",
    # ─────────────────────────────────────────────────
    "https://womanlike-utter-turbofan.ngrok-free.dev",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Application definition

INSTALLED_APPS = [
    "channels",
    "live_class",
    "students",
    "notifications",
    "attendance",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "teachers",
    "colleges",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # ── WhiteNoise: static files fast serve karto (CSS/JS/models cache hotat) ──
    # pip install whitenoise
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # ─────────────────────────────────────────────────────────────────────────
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MirrorMind.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MirrorMind.wsgi.application"
ASGI_APPLICATION = "MirrorMind.asgi.application"

# ════════════════════════════════════════════════════════════════
# CHANNEL LAYERS
# ────────────────────────────────────────────────────────────────
# PROBLEM: InMemoryChannelLayer fakt single-process madhe kaam
# karto. Multiple workers (Gunicorn/Daphne) asatana WebSocket
# messages dusrya process la pohochat nahin → class connect hot
# nahi, lag yeto, disconnect hoto.
#
# FIX: Redis Channel Layer vaapar.
#
# Setup karayala:
#   pip install channels-redis
#   Redis server chalvun thev (local: redis-server)
#
# Deploy keltyanar Redis URL .env madhe takavat:
#   REDIS_URL=redis://127.0.0.1:6379
#
# Khali Redis config comment kadhun dakhav aani
# InMemory config comment kara.
# ════════════════════════════════════════════════════════════════

# ── OPTION 1: Redis (Production / Multi-worker deploy saathi) ──
# REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379")
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [REDIS_URL],
#             "capacity": 1500,          # max messages per channel
#             "expiry": 10,              # seconds before undelivered msg drops
#         },
#     }
# }

# ── OPTION 2: InMemory (Local testing / single-process saathi) ──
# Note: ngrok + daphne single process madhe he theek kaam karto.
# Deploy keltyanar OPTION 1 uncomment kara, ha comment kara.
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# ── WhiteNoise: Static files compress + cache karto ──────────────────────
# Face-API model files (shard1 files ~1-2MB) browser cache madhe save
# hotil → page reload var punha download hoynar nahin → lag kami hoil.
# pip install whitenoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise cache: 1 day (86400 seconds)
# Face-API models, CSS, JS browser madhe cache hoil
WHITENOISE_MAX_AGE = 86400

# Brotli compression enable (optional, faster than gzip):
# pip install whitenoise[brotli]
WHITENOISE_USE_FINDERS = True
# ─────────────────────────────────────────────────────────────────────────

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================
# EMAIL CONFIGURATION (SMTP via Gmail)
# Set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in .env
# ============================================================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# ============================================================
# CRONTAB CONFIGURATION
# Runs every 5 minutes to send class reminder emails
#
# Setup:
#   pip install django-crontab
#   Add 'django_crontab' to INSTALLED_APPS
#   Run: python manage.py crontab add
# ============================================================
CRONJOBS = [
    (
        "*/5 * * * *",
        "django.core.management.call_command",
        ["send_class_reminders"],
        {},
        ">> /tmp/mirrormind_cron.log 2>&1",
    )
]

# ============================================================
# LOGGING CONFIGURATION
# DEBUG=True astaana sabkahi log hoto
# DEBUG=False (production) astaana fakt WARNING+ log hote
# ============================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "mirrormind": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}
