# Generated by Django 5.2.11 on 2026-03-23 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('qualification', models.CharField(blank=True, choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=50, null=True)),
                ('experience', models.CharField(blank=True, choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.class', verbose_name='Class')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_courseallocation',
                'unique_together': {('teacher', 'class_assigned', 'subject_name', 'academic_year')},
            },
        ),
    ]
