# Generated by Django 5.2.11 on 2026-03-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('meeting_platform', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.courseallocation')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teachers.teacher')),
            ],
            options={
                'db_table': 'notification_classschedule',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('Happy', 'Happy'), ('Focused', 'Focused'), ('Neutral', 'Neutral'), ('Bored', 'Bored'), ('Sad', 'Sad'), ('Sleepy', 'Sleepy'), ('Unavailable', 'Unavailable')], default='Neutral', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='notifications.classschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='students.student')),
            ],
            options={
                'db_table': 'notification_emotionlog',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['schedule', 'student'], name='notificatio_schedul_fbe13e_idx'), models.Index(fields=['schedule', 'logged_at'], name='notificatio_schedul_730df4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('schedule_created', 'New Class Scheduled'), ('schedule_updated', 'Schedule Updated'), ('schedule_cancelled', 'Class Cancelled'), ('class_started', 'Class Started'), ('class_ended', 'Class Ended'), ('class_reminder', 'Class Reminder'), ('teacher_notification', 'Teacher Notification'), ('reminder', 'Reminder')], default='teacher_notification', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.class')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.classschedule')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='teachers.teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student')),
            ],
            options={
                'db_table': 'notification_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_read'], name='notificatio_student_afa3da_idx'), models.Index(fields=['class_target', 'created_at'], name='notificatio_class_t_77a75c_idx')],
            },
        ),
    ]
